### ISSUE TITLE
Extension of ShapeFormer towards higher resolution

### ISSUE THREAD

**Issue by dqj5182** [QhelDIV/ShapeFormer#24]
Is there a reason why ShapeFormer implemented only on 64 resolution feature grid? Would there be performance boost if it is further extended to 128 resolution feature grid?

Would increasing the number of points from Xtg, Ytg allow performance boost?

My question was largely from the name of Imnet2LowResDataset class. Wondering whether low resolution was intended.

**Comment by QhelDIV** [comment]
Hi, thanks for your question.
First of all, I think what you are describing is not the 'feature grid', but rather 'occupancy grid', which stores the ground truth occupancy samples.
When using a higher resolution, thin structures are much harder to recover (we tried to directly use 256 resolution probes, and it is hard to train)
This also correlates to the feature resolution. The feature resolution used in the paper is 16, which means the VQDIF module have to learn compression from 64 resolution to 16 resolution, which is much easier than 256 -> 16. 

I think 128 would work fine since 8x compression is reasonable, but you need to give it a try.

**Comment by dqj5182** [comment]
Thanks for your detailed explanation!
Really helped me to guide on how to further develop your model.
